In [1]:
import numpy as np

Point 1

In [2]:
u = np.array( [ 2, 7, 1 ] )
v = np.array( [ -3, 0, 4 ] )
w = np.array( [ 0, 5, -8 ] )

In [3]:
u + v + v

array([-4,  7,  9])

In [5]:
u + 3 * v - 5 * w

array([ -7, -18,  53])

Point 2

In [6]:
u = np.array( [ 3, -2, 1, 4 ] )
v = np.array( [ 7, 1, -3, 6 ] )

In [7]:
u + v

array([10, -1, -2, 10])

In [8]:
u - v

array([-4, -3,  4, -2])

In [9]:
u + 3 * v

array([24,  1, -8, 22])

In [12]:
np.dot( u, v )

40

In [16]:
np.linalg.norm( u )

5.477225575051661

In [17]:
np.sqrt( 30 )

5.477225575051661

In [18]:
np.linalg.norm( u - v )

6.708203932499369

In [20]:
np.sqrt( 45 )

6.708203932499369

Point 3

Point 4

Point 5

Point 6

Point 7

In [22]:
np.linalg.norm( np.array( [ 2, 2 ] ) )

2.8284271247461903

In [23]:
2 * np.sqrt( 2 )

2.8284271247461903

In [24]:
np.linalg.norm( np.array( [ 2, 2 * np.sqrt( 3 ) ] ) )

3.9999999999999996

In [25]:
np.linalg.norm( np.array( [ -2 * np.sqrt( 3 ), 2 ] ) )

3.9999999999999996

In [26]:
np.linalg.norm( np.array( [ -3, -3 ] ) )

4.242640687119285

In [27]:
3 * np.sqrt( 2 )

4.242640687119286

In [28]:
np.linalg.norm( np.array( [ 6, -6 ] ) )

8.48528137423857

In [29]:
3 * np.sqrt( 8 )

8.485281374238571

In [30]:
np.linalg.norm( np.array( [ 0, 3 ] ) )

3.0

Point 8

In [33]:
z = 2 + 3j
w = 5 - 2j

In [34]:
z + w

(7+1j)

In [35]:
np.dot( z, w )

(16+11j)

In [36]:
z - 2 * w

(-8+7j)

In [37]:
np.linalg.norm( z )

3.605551275463989

In [38]:
np.sqrt( 13 )

3.605551275463989

Point 9

In [39]:
z = 2 + 3j
w = 12 -5j

In [40]:
np.linalg.norm( z )

3.605551275463989

In [41]:
np.sqrt( 13 )

3.605551275463989

In [42]:
np.linalg.norm( w )

13.0

In [43]:
np.sqrt( 169 )

13.0

In [44]:
z + w

(14-2j)

In [45]:
np.dot( z, w )

(39+26j)

Point 10

In [48]:
np.array( [ 3, -4, 5 ] ) + np.array( [ 1, 1, -2 ] )

array([ 4, -3,  3])

In [50]:
-3 * np.array( [ 4, -5, -6 ] )

array([-12,  15,  18])

In [51]:
-1 * np.array( [ -6, 7, -8 ] )

array([ 6, -7,  8])

Point 11

In [52]:
np.dot( np.array( [ 2, 3, -6 ] ), np.array( [ 8, 2, -3 ] ) )

40

In [53]:
np.dot( np.array( [ 3, -5, 2, 1 ] ), np.array( [ 4, 1, -2, 5 ] ) )

8

Point 12

Point 13

In [54]:
np.linalg.norm( np.array( [ 1, 7 ] ) - np.array( [ 6, -5 ] ) )

13.0

In [55]:
np.linalg.norm( np.array( [ 3, -5, 4 ] ) - np.array( [ 6, 2, -1 ] ) )

9.1104335791443

In [56]:
np.sqrt( 83 )

9.1104335791443

In [57]:
np.linalg.norm( np.array( [ 5, 3, -2, -4, -1 ] ) - np.array( [ 2, -1, 0, -7, 2 ] ) )

6.855654600401044

In [59]:
np.sqrt( 47 )

6.855654600401044

Point 14

In [60]:
np.linalg.norm( np.array( [ 2, -7 ] ) )

7.280109889280518

In [61]:
np.sqrt( 53 )

7.280109889280518

In [62]:
np.linalg.norm( np.array( [ 3, -12, -4 ] ) )

13.0

Point 15

In [63]:
np.linalg.norm( np.array( [ -4, 5 ] ) )

6.4031242374328485

In [64]:
np.sqrt( 41 )

6.4031242374328485

In [65]:
np.linalg.norm( np.array( [ 4, 3 * np.sqrt( 7 ) ] ) )

8.888194417315589

In [66]:
np.sqrt( 79 )

8.888194417315589

In [67]:
np.linalg.norm( np.array( [ -7 * np.sqrt( 7 ), -2 ] ) )

18.62793601019716

In [68]:
np.sqrt( 347 )

18.627936010197157

In [69]:
np.linalg.norm( np.array( [ -4, -7 ] ) )

8.06225774829855

In [70]:
np.sqrt( 65 )

8.06225774829855

In [71]:
np.linalg.norm( np.array( [ 6, -4 ] ) )

7.211102550927978

In [72]:
np.sqrt( 52 )

7.211102550927978

In [73]:
np.linalg.norm( np.array( [ 10, 7 ] ) )

12.206555615733702

In [74]:
np.sqrt( 149 )

12.206555615733702

Point 16

In [75]:
z = 2 - 3j
w = 4 + 5j

In [76]:
z + w

(6+2j)

In [77]:
np.dot( z, w )

(23-2j)

In [78]:
np.linalg.norm( z )

3.605551275463989

In [80]:
np.sqrt( 13 )

3.605551275463989

In [79]:
np.linalg.norm( w )

6.4031242374328485

In [81]:
np.sqrt( 41 )

6.4031242374328485

Point 17

In [90]:
np.dot( np.array( [ 2, 0, -3 ] ), np.array( [ 4, 0, 2 ] ) )

2

In [91]:
np.dot( np.array( [ 4, 1, 5 ] ), np.array( [ 7, 2, -3 ] ) )

15

In [92]:
np.dot( np.array( [ 2, 0, 3 ] ), np.array( [ 7, 2, -3 ] ) )

5